# Change these first
owner: LucaRosaldi
repo: p1-uptime-robot

sites:
  - name: PubliOne
    url: https://publione.it
  - name: Casta
    url: https://casta.com

status-website:
  baseUrl: /p1-uptime-robot
  logoUrl: https://publione.it/app/uploads/2021/09/p1-symbol.svg
  name: PubliOne
  introTitle: "Uptime monitor and status page for PubliOne websites."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/LucaRosaldi/p1-uptime-robot).
  navbar:
    - title: PubliOne
      href: https://publione.it
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
